package org.training.calculator.exception;

public class TaskCompletedException extends RuntimeException {
}
